# Generated by Django 5.1.7 on 2025-04-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listings', '0002_remove_car_additional_images_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='media/cars/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='media/cars/'),
        ),
    ]
